- docs/overview/changes.md
- docs/syntax/scss.md
See https://github.com/Financial-Times/o-ft-forms/issues/72
From [all the existing pseudo classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes#Index_of_standard_pseudo-classes), I couldn't find any other than `:not()` that would create specificity issues unnecessarily.
I suggest we restrict the spec to that particular case for now to keep it simple, and to amend if we have problems with other pseudo classes in the future.
> :not() pseudo class should not be used

- docs/overview/roadmap.md
- docs/syntax/scss.md
> Modules *should* be documented using SassDoc comments
Since we don't impose JSDoc, I figured we couldn't be requiring SassDoc with a **must** keyword. Thoughts?
Fixes #287
> Update roadmap and add SassDoc to the SCSS specification - fixes #287

- docs/component-spec/modules.md
- docs/developer-guide/building-modules.md
- docs/developer-guide/using-modules.md
- examples/ctm.html
Following Origami meeting last week.
We discussed using `getComputedStyle`, however, that has partial support in fairly old browsers, and is also supported in Opera Mini.  I've instead used the BBC's CTM test from their original post, which is IE9+ and does not include Opera Mini (and also tests features we're more likely to actually need)
> Recommend a specific CTM test which meets the FT browser support policy

- docs/developer-guide/building-modules.md
- examples/ctm.html
During the workshop we had to tell everybody to load webfonts and icons. That's something we can streamline by putting it by default in the examples that are going to get copy-pasted
> Add icons and font modules as default modules in the examples

- docs/developer-guide/build-service.md
It's only a small change, but might prove useful to others as I'd missed the bit about boiler plate code and it's not mentioned that you should paste this into your jsbin later on in the docs, but is relied upon to be there.
> Adding minor instruction to clarify build service docs

- _layouts/default.html
- o-fonts doesn't have any JS
- HighlightJS replaces Prettify for syntax highlighting and is bundled in o-techdocs
> Remove unnecessary JavaScript and update modules

- examples/ctm.html
- Remove comments on uber-advanced loading techniques (that products usually don't implement anyway, and if they do it means they know what they are doing)
- Add a comment on the fact we're loading fonts and icons
In answer to @triblondon's [comment](https://github.com/Financial-Times/ft-origami/pull/336/files#r26965034).
@triblondon is this enough or should we add additional explanations?
> Update Origami stylesheet loading inline documentation

- docs/developer-guide/building-modules.md
Ran into this issue myself when reproducing the manual build steps.
See http://stackoverflow.com/questions/24534974/emalformed-failed-to-read-bower-json-unexpected-token
> Add Windows compatibility notice for bower configuration files

- docs/3rd-party-a-list.md
- docs/developer-guide/general-best-practices.md
- docs/syntax/js.md
- docs/syntax/scss.md
- docs/syntax/web-service-description.md
- docs/syntax/web-service-index.md
I've been reading through the documentation and I found a few minor issues (which are a lot easier to spot to a fresh pair of eyes) that I thought I should point out.
In this PR, I've included the trivial things that I was able to fix myself (mostly related to Markdown parsing and a couple of typos), but there are a couple of others that would require further information and decisions from you.
1. In [General best practices](http://origami.ft.com/docs/developer-guide/general-best-practices/#browser-support), there's a link to a private [Google Docs file](https://docs.google.com/a/ft.com/document/d/1dX92MPm9ZNY2jqFidWf_E6V4S6pLkydjcPmk5F989YI/edit), not sure if intentionally;
1. In [Core vs Enhanced experience](http://origami.ft.com/docs/developer-guide/using-modules/#core-vs-enhanced-exper …
> Fix small issues in documentation pages

- docs/syntax/js.md
Closes https://github.com/Financial-Times/ft-origami/issues/383
> Restrict JS to ES 6 and below, closes #383

- _layouts/default.html
- docs/developer-guide/building-modules.md
- docs/developer-guide/general-best-practices.md
- examples/ctm.html
See http://www.google.com/chromeframe/about/:
> Thank you for stopping by
> 
> We've wound down Chrome Frame and ceased support. Please read our previous announcement for more information. If you haven't already, consider installing and using a modern browser to get the best of the web.
> 
> For more developer information please see the FAQ.
> 
> Sincerely,
> 
> The Google Chrome Frame team
> End chromeframe support

- docs/developer-guide/building-modules.md
Summary:
* Remove first option for installing node
* Add a link for troubleshooting guide for both Node and Ruby
* Add note about removing node_modules & bower_components if verify errors
* Remove watch from default task
* Link to git protocol fix
* Remove c9 from recommendations
* Change public/index.html to index.html
CC @AlbertoElias
> Manual guide fixes

- docs/3rd-party-a-list.md
Kramdown Markdown parser generates anchors using dashes
> Fixing the anchor links in the 3rd-party A list

- docs/component-spec/modules.md
- docs/developer-guide/building-modules.md
This PR:
- Fixes two typos, I believe these should both say "bower"
- Trims some trailing whitespace in building_modules.md (which Atom did automatically and without my noticing but I guess nobody's going to mind)
> Fix two typos in "bower"

- docs/component-spec/modules.md
- docs/component-spec/web-services.md
- docs/syntax/html.md
- docs/syntax/js.md
- docs/syntax/scss.md
According to RFC2119 SHOULD NOT has a particular meaning and so I think both
"should" and "not" should be emphasized here rather than just "should"
> Correct emphasis

- index.md
Just noticed a broken link to the components registry. Updated link and link text to reflect new location.
> Fix broken link to registry

- docs/developer-guide/general-best-practices.md
- docs/developer-guide/index.md
- docs/syntax/js.md
- docs/syntax/scss.md
- fix a typo
- fix a recently introduced bug with parsing markdown, where headings without a space between the text and the hash are not parsed at all.
> Fix broken mark down / typo

- guidelines/2016-03-08-github-guidelines.md
- guidelines/temp.md
Add draft guideline on how to use Issues/Pull requests templates in a repository as it is a new addition to GitHub.
See [template-test](https://github.com/j-mes/template-test/) as an example.
Feedback would be much appreciated!
Closes #450.
> Add draft copy of Issues/Pull Request templates

- _includes/header.html
- _includes/home-banner.html
- _layouts/default.html
- docs/component-spec/index.md
- docs/developer-guide/index.md
- docs/developer-guide/using-modules.md
- docs/syntax/html.md
Fixes #444 
Here's a first go at changing the docs for the core vs enhanced example in the developer guide. I've also updated the homepage banner and titles for the developer guide and spec landing pages.
> Update spec and dev guide titles and core vs enhanced docs for devs

- docs/component-spec/modules.md
We broke bundles when adding o-ft-icons to o-buttons, and we must prevent this
> Add rule to make major release when adding new dep

- new-starter-guide/2016-03-15-new-starter-to-origami.md
- new-starter-guide/new-starter-to-origami.md
I've added a first draft of the new starter guide that's more specific to Origami.
This needs some reviewing from @Financial-Times/origami-core :+1:. This can be relocated in a better place in the documentation later when it has been ratified.
> Add new starter guide documentation 1st draft

- _includes/footer.html
- index.md
Just came across those two changes and one of them did not feel right to me.
Also spotted a mistake that may have been overlooked with a double 'a' for 'a a CDN' part in the main page.
> Minor changes

- docs/developer-guide/building-modules.md
This fixes a small bug when following along the docs for the
first time. Without the silent flag the header does not render
correctly.
> Use non-silent header in example main.scss

- docs/developer-guide/building-modules.md
- main.scss
We're calling benton but not using it.
I've also upated a code example to use metric too, though this example should
be looked at seperately to make sure it still works as I think the font stack
has changed anyway.
> Remove Benton override

- docs/developer-guide/building-modules.md
- main.scss
Reverts Financial-Times/ft-origami#489
(This was actually needed... oops)
> Revert "Remove Benton override"

- Makefile
- README.md
Fixes a part of the accessibility tests by ignoring the search box on the website via `make test` with Pa11y.
Reference: #487.
> Add --hide-elements flag for search box

- docs/component-spec/modules.md
#496 
This adds a little step-by-step guide under **Managing releases** about what can be done for deprecation of a module.
> Add deprecation guide under docs/component-spec/

- .pa11yci
- Makefile
- README.md
Pa11y CI is more geared towards what we're doing here, and it also has sitemap support built in. So we can reduce a bunch of boilerplate code.
Also the test part of the build now takes ~15s instead of ~40s as we can test multiple pages in parallel with Pa11y CI.
> Switch from Pa11y to Pa11y CI

- docs/syntax/origamijson.md
This specs the origamiCategory property in the origami.json.
Unsure whether to put something about how we define which category a module belongs to.
> Add origami category to origami.json specification

- docs/syntax/origamijson.md
Also tidies up the example json at the bottom of the page.
> Update the `origami.json` guidelines with `hidden` and `display_html` properties

- docs/developer-guide/quick-start-guide.md
Changes the `<script>` tags to open/close tags instead of self-closing tags.
> Fix script tags in quick start guide

- index.md
They are now using a system inspired by Origami but no longer a fork of it.
> Remove Pearson Higher Ed from users

- docs/component-spec/web-services.md
None of our services were meeting the spec, including the older
ones. I've updated the spec to include new standards that we employ, and
to reflect the way we're actually building services.
> Update the services spec to match all current services

- _layouts/default.html
Brackets are a bit confusing in headings, so switching them to capitals. 
I have also shortened the navigation headings from `Modules quick start` to `Quick start`. And from `Using the build service` to `Build service`.
> Copy change - take brackets out of navigation text

- docs/developer-guide/choosing-your-build-method.md
Just to make a simple version of the options clearer at the top of this page, have added a 1,2,3 list at the top, then if people want to go down into the table they can.
> Copy change - Add options paragraph to Pick Build Method page

- docs/developer-guide/build-service.md
In some ways jsbin is an implementation detail. What you need to do is create a css/html/js file. So have just swapped this out of the title.
> Copy change - take jsbin out of title

- docs/syntax/origamijson.md
I noticed that we have a third type of component in the registry, labelled as `imageset` component's in their `origami.json` file. This is not currently in the Origami specification and should be added.
> WIP - Add imageset to the spec as an origami component type

- docs/syntax/origamijson.md
This introduces a new `supportContact` property in the origami.json
spec. This property is used to document support contact details of the
team that maintains a component or service. It also deprecates the use
of an email address in the `support` property.
I'm proposing this so that the support details of a component are more
strict and readily machine-readable - we need this for the repo data
service, which will use the information to differentiate between Origami
components that are maintained by the Origami team vs another team.
The `support` property is also nearly always a GitHub issues URL in
our components, which means contact details are stored nowhere in
the repository.
Probably easier to review as a diff on the rendered markdown: …
> Propose a new "supportContact" property

- docs/component-spec/modules.md
Avoids documenting OBT in ft-origami as this is likely to become outdated.
> OBT instructions outdated
