docs/component-spec/modules.md
- Update the directory structure to the latest common usage
- Set expectations on "what is a module" earlier in the documentation by putting the directory structure at the top of the page
- Give developers an easy way to generate that suggested directory structure
=> Surface directory structure and give an easy way to create it quickly

docs/syntax/js.md
http://kangax.github.io/compat-table/es5/ IE9 supports it
=> Suggestion to assume ES5 support

docs/component-spec/web-services.md, docs/syntax/metrics.md
Proposed change to the standard to specify how services should report metrics.
=> Metrics should now use Graphite

docs/syntax/html.md, docs/syntax/js.md
In this PR I've also worked on the definition of owned DOM.  I think our current working practice aligns with what I've written here, and think this is worth clarifying in the spec.
=> Clarify component configuration rules, closes #344. Clean up definition of owned DOM

docs/3rd-party-a-list.md
Next has been `fetch`ing for several months.  It's nice.  Highly recommend.
=> Recommend fetch for ajax

docs/component-spec/modules.md
Pending [this](https://github.com/Financial-Times/origami-build-tools/pull/255) other pr
=> Use documentClasses instead of bodyClasses

index.md
Please add comments to this document if any new teams are using Origami: https://docs.google.com/document/d/1VGzgABmXjNr9rXARn1BteIcjPzhpjsj1zcd6xyw3Bso/edit#
=> Who's using Origami?

docs/syntax/js.md
=> Add note about imperative configuration options in global config blocks

docs/developer-guide/building-modules.md
So lintspaces doesn't complain.
Also added syntax highlighting.
=> Add newlines to the end of code blocks

docs/developer-guide/building-modules.md
For some reason the codeblocks were breaking so I've reverted to using tab indentation instead of the triple tick.
Just did a pull with your changes from #405
=> Fix codeblocks

docs/component-spec/modules.md, docs/developer-guide/building-modules.md, docs/developer-guide/general-best-practices.md, docs/syntax/js.md, examples/travis.yml
=> Updates from JSHint to ESLint and to Webpack

docs/developer-guide/building-modules.md
Does this make sense in the flow of the guide?
CC @AlbertoElias
=> Add aside on cloning boilerplate

docs/overview/governance.md
The whitespace character here is non-breaking, so it doesn't collapse down at
the beginning of the title. Change this to be a breaking space.
=> Fix whitespace

docs/developer-guide/build-service.md
Bigger changes coming to this page, but I just want to get these two completely uncontroversial fixes in first.
=> fix two typos

docs/component-spec/modules.md
Would love to hear feedback on wording
=> Adds release checklist to module spec

docs/developer-guide/general-best-practices.md
=> Add SVG example from ft-icons docs

README.md
Add a guide for writing style for Origami's tech docs.
This is a short guide rather than something that contains a lot of 'why'. For more information on why these are good rules to follow, consult: https://jacobian.org/writing/great-documentation/
=> Document writing style

examples/build-service-tutorial-boilerplate.html
Sorry, that's my OCD kicking in. When reading the new (and great) documentation pages, things weren't aligned properly.
=> Fix indentation

docs/developer-guide/building-modules.md
=> fix broken links

docs/developer-guide/building-modules.md
Developer guide update (o-icons name and version updated and bug in a command line fixed)
=> Developer guide

docs/component-spec/modules.md
Moves to circle and removes demo config
=> Updates file structure and command to start component

_includes/header.html
See: https://github.com/Financial-Times/origami-registry/pull/14
=> Update nav to be inline with Registry nav

_includes/header.html, main.scss
=> remove the subnav as these links have been moved into the topnav now

docs/component-spec/modules.md
=> Add version advice when requiring a new browser api polyfill

Makefile, _config.yml, docs/component-spec/modules.md, package-lock.json, package.json
- Update our spec: https://github.com/Financial-Times/ft-origami/issues/549
- Accidentally (but acceptably ?) commit `package-lock.json` https://docs.npmjs.com/files/package-lock.json
=> Update component feature deprecation guide.

README.md
Original post on Wayback Machine https://web.archive.org/web/20170115154853/https://jacobian.org/writing/great-documentation/
=> Link to the individual posts as the original post 404s - Fixes #551

index.md
This paragraph could help the reader more by coming at things from where they're coming from - wanting to include origami in a project. 
Hopefully this rewrite will make it clearer what these tools can do for them.
=> Copy change - make paragraph more user focussed

circle.yml
=> Correct the base branch
